name: footballtracking_app
description: "Football tracking app using the movesense_plus plugin."
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.0.0
  shared_preferences: ^2.2.3

  # Henter movesense_plus direkte fra GitHub-repoet
  movesense_plus:
    git:
      url: https://github.com/carp-dk/flutter-plugins.git
      path: packages/movesense_plus

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
